# Generated by Django 5.0.4 on 2024-05-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(default='default.jpg', upload_to='company_logo/'),
            preserve_default=False,
        ),
    ]
