# Generated by Django 5.0.4 on 2024-06-25 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to='uploads/logo/'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='Nigeria', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='date_enrolled',
            field=models.DateField(default=datetime.datetime(2024, 6, 25, 19, 53, 53, 257846, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(default=110112, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='Lagos State', max_length=300),
        ),
    ]
