# Generated by Django 5.0.4 on 2024-06-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(blank=True, default='uploads/default.png', upload_to='uploads/logo/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_enrolled',
            field=models.DateField(blank=True),
        ),
    ]
