# Generated by Django 5.0.4 on 2024-05-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_company_logo_remove_user_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rc_number',
            field=models.CharField(max_length=20),
        ),
    ]
