# Generated by Django 5.0.4 on 2024-06-25 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_date_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='account.sector'),
        ),
    ]
