version: '3.8'

services:
  eportal:
    build:
      context: .
      dockerfile: Dockerfile.prod
      image: o3cloudng/MaximunCollection
    command: gunicorn nsib.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/django/web/static
      - media_volume:/home/django/web/media
    expose:
      - 8000
    env_file:
      - ./.env
      
  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/django/web/static
      - media_volume:/home/django/web/media
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - eportal

  acme-companion:
    image: nginxproxy/acme-companion
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme: