# Generated by Django 5.0.4 on 2024-05-20 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infra_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceid', models.CharField(max_length=200)),
                ('infra_type', models.CharField(max_length=200)),
                ('add_from', models.CharField(max_length=200)),
                ('add_to', models.CharField(max_length=200)),
                ('length', models.CharField(max_length=200, null=True)),
                ('year_installed', models.CharField(max_length=200)),
                ('upload_application_letter', models.FileField(upload_to='uploads/applications/')),
                ('upload_asBuilt_drawing', models.FileField(upload_to='uploads/drawings/')),
                ('upload_payment_receipt', models.FileField(upload_to='uploads/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
