# Generated by Django 5.0.4 on 2024-06-03 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infra_name', models.CharField(max_length=200)),
                ('rate', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceid', models.CharField(max_length=200, null=True)),
                ('infra_type', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('length', models.CharField(max_length=200, null=True)),
                ('add_from', models.CharField(max_length=200)),
                ('add_to', models.CharField(max_length=200)),
                ('year_installed', models.DateField(max_length=200)),
                ('upload_application_letter', models.FileField(blank=True, null=True, upload_to='uploads/applications/')),
                ('upload_asBuilt_drawing', models.FileField(blank=True, null=True, upload_to='uploads/drawings/')),
                ('upload_payment_receipt', models.FileField(blank=True, null=True, upload_to='uploads/receipts/')),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('DISPUTED', 'Disputed'), ('RESOLVED', 'Resolved')], default='UNPAID', max_length=10)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
