# Generated by Django 5.0.4 on 2024-05-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='year_installed',
            field=models.DateField(max_length=200),
        ),
    ]
