# Generated by Django 5.0.4 on 2024-06-04 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='is_disputed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permit',
            name='infra_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infra_type', to='tax.infrastructuretype'),
        ),
    ]
