# Generated by Django 5.0.4 on 2024-05-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='amount',
            field=models.CharField(default=10, max_length=200),
            preserve_default=False,
        ),
    ]
