# Generated by Django 5.0.4 on 2024-05-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_permit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='upload_application_letter',
            field=models.FileField(blank=True, null=True, upload_to='uploads/applications/'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='upload_asBuilt_drawing',
            field=models.FileField(blank=True, null=True, upload_to='uploads/drawings/'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='upload_payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='uploads/receipts/'),
        ),
    ]
