# Generated by Django 5.0.4 on 2024-06-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_permit_is_disputed_alter_permit_infra_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='infra_cost',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
