# Generated by Django 5.0.4 on 2024-06-05 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_permit_infra_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave_amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('referenceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='tax.permit')),
            ],
        ),
    ]
