# Generated by Django 5.0.4 on 2024-05-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0004_alter_permit_company_alter_permit_referenceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
