# Generated by Django 5.0.4 on 2024-06-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0007_alter_permit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permit',
            name='is_revised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permit',
            name='is_undisputed',
            field=models.BooleanField(default=False),
        ),
    ]
