# Generated by Django 5.0.4 on 2024-06-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0008_permit_is_paid_permit_is_revised_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='is_existing',
            field=models.BooleanField(default=False),
        ),
    ]
