# Generated by Django 5.0.4 on 2024-06-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0009_permit_is_existing'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permit',
            name='add_from',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='permit',
            name='add_to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='permit',
            name='amount',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='length',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
