# Generated by Django 5.0.4 on 2024-06-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0010_permit_age_alter_permit_add_from_alter_permit_add_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='amount',
            field=models.IntegerField(default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='length',
            field=models.IntegerField(default=0, max_length=200, null=True),
        ),
    ]
