# Generated by Django 5.0.4 on 2024-06-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0011_alter_permit_amount_alter_permit_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='waver',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='uploads/receipts/'),
        ),
    ]
