# Generated by Django 5.0.4 on 2024-06-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0015_alter_permit_infra_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='infra_cost',
            field=models.IntegerField(default=0),
        ),
    ]
