# Generated by Django 5.0.4 on 2024-06-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0018_alter_remittance_remitted_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittance',
            name='apply_for_waver',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
